### ISSUE TITLE
Key padding mask for Triton version 

### ISSUE THREAD

**Issue by EBGU** [HazyResearch/flash-attention#104]
Hi!
I found your FlashAttention really interesting! I am currently working with models that have attention bias, so I am looking at your triton version. I wonder how I could pass a key padding mask to the following function. Should I masked_fill the bias with float('-inf')? Thank you!

class FlashAttnFunc(torch.autograd.Function):
    @staticmethod
    def forward(ctx, q, k, v, bias=None, causal=False, softmax_scale=None):

**Comment by tridao** [comment]
Yes, the bias is [added](https://github.com/HazyResearch/flash-attention/blob/5d079fdd7a20bbd354080a80b20b5c36c93898d4/flash_attn/flash_attn_triton.py#L168) to Q @ K^T, so you can fill the bias with `-inf` to mask out the keys. In this case the bias should have shape (batch, 1, 1, seqlen_k)
