### ISSUE TITLE
Long sequences support

### ISSUE THREAD

**Issue by kuizhiqing** [HazyResearch/flash-attention#115]
First, thank your for your awesome project.

I've found that you are developing an optimized version to support long sequences up to 8k and more, ref https://crfm.stanford.edu/2023/01/13/flashattention.html.

Well, it seems the related codes does not merge to this repos yet, do you have any plan with it ?

Thanks.

**Comment by tridao** [comment]
The current implementation in this repo is the latest version that contains optimization for sequences beyond 8k.
Could you clarify "related codes"?
