### ISSUE TITLE
Keep Attention Softmax FP32 during FP16 Training

### ISSUE THREAD

**Issue by prnake** [HazyResearch/flash-attention#118]
Thanks a lot for your great work!

How difficult would it be to modify the kernels to only keep the attention softmax calculation at fp32 precision? Like the implementation of FusedScaleMaskSoftmax in Megatron-LM.

**Comment by tridao** [comment]
The attention softmax calculation is already done at fp32 precision.
The inputs (q, k, v) and output are in fp16/bf16.
You can compare 
(FlashAttention - standard impl in fp32) vs (standard impl in fp16/bf16 - standard impl in fp32)
as we do [here](https://github.com/HazyResearch/flash-attention/blob/06da275bcba0f4554f205f52fa20f74309f2d973/tests/test_flash_attn.py#L424).
The two numerical errors are usually around the same.

**Comment by prnake** [comment]
Thanks for your reply, I'll try testing it.
