### ISSUE TITLE
Bert or GPT2 example

### ISSUE THREAD

**Issue by SeaOfOcean** [HazyResearch/flash-attention#12]
Hi I see your experiments on Bert and GPT2 with flash-attention, can you provide the sample code of Bert or GPT example with flash-attention instead of standard attention? Thanks!

**Comment by Jack47** [comment]
It would be great if GPT2 example with flash attention integrated released in github, I see in [openreview authors said](https://openreview.net/forum?id=H4DqfPSibmx&noteId=lA1gAlhBPYR) they will public the experiment source code after review.

**Comment by tridao** [comment]
It's available here: https://github.com/tridao/zoo/blob/main/src/models/gpt2.py
[GPT2/GPT3 and ViT examples].
I might start moving the examples to this repo.
