### ISSUE TITLE
GPT-J style fused rotary

### ISSUE THREAD

**Issue by kurumuz** [HazyResearch/flash-attention#126]
HI,

The current implementation seems to use the GPT-NeoX style rotary, which is numerically different than what GPT-J uses.
From what I understand the main difference is how the tensors are rotated, NeoX one splits in half and rotates, meanwhile GPT-J one interleaves.

Is it possible to get GPT-J fused rotary implementation in flash-attention? Thanks.

**Comment by tridao** [comment]
I've been traveling but might have some time this weekend to take a look.
It's probably not hard to implement, might just need to change the Pytorch code without touching CUDA.

**Comment by tridao** [comment]
@kurumuz GPT-J style rotary is now implemented in the latest [commit](https://github.com/HazyResearch/flash-attention/commit/e45a46a5b767d76e14c76e4bfac408b7cf94d896).

**Comment by kurumuz** [comment]
Thanks, Awesome 🙂 Closing the issue.
