### ISSUE TITLE
No module named 'xentropy_cuda_lib'

### ISSUE THREAD

**Issue by zhuzn** [HazyResearch/flash-attention#128]
when I use `from flash_attn.losses.cross_entropy import CrossEntropyLoss as FlashCrossEntropyLoss`, I get a error, `ModuleNotFoundError: No module named 'xentropy_cuda_lib`. I don't find xentropy_cuda_lib that I use conda or pip. how do i install xentropy_cuda_lib？
Thanks

**Comment by tridao** [comment]
You can do `cd csrc/xentropy && pip install .`.
We have some of the instructions [here](https://github.com/HazyResearch/flash-attention/tree/main/training) but we'll eventually move them to the main README.

**Comment by zhuzn** [comment]
Thanks for your reply, I'll try testing it.
