### ISSUE TITLE
Running on T4 (AWS EC2)

### ISSUE THREAD

**Issue by baskrahmer** [HazyResearch/flash-attention#143]
Firstly big thanks for the great work and open source library, very cool stuff!!

I am trying to integrate this on a T4 instance on AWS. Running the code gives the following error:

```
.venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 42, in _flash_attn_backward
    _, _, _, softmax_d = flash_attn_cuda.bwd(
RuntimeError: Expected is_sm80 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

Also when installing from source and removing the sm_80 flags, a similar error appears:

```
.venv/lib/python3.10/site-packages/flash_attn-0.2.8-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 42, in _flash_attn_backward
    _, _, _, softmax_d = flash_attn_cuda.bwd(
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

Any idea what causes this expectation of is_sm80 to be True? I will try running this on an A100 to see if that fixes things.

**Comment by baskrahmer** [comment]
Thanks for the quick reply! The head dimension is 16; I'm running a custom version of the 1.3B GPT-Neo model from HuggingFace, similar to https://github.com/HazyResearch/flash-attention/issues/138

I also tried with Torch context managers as https://github.com/pytorch/pytorch/issues/94883

Will report A100 results here; that should indicate if it is hardware-specific

**Comment by tridao** [comment]
I think 1.3B GPT-Neo has 16 heads, hidden dim = 2048, so **each head has dimension = 128**.

**Comment by baskrahmer** [comment]
Ahh that makes 100% sense; I mixed it up with num_heads. Thank you very much for the help!
