### ISSUE TITLE
supporting fused rms norm for hidden size > 6144

### ISSUE THREAD

**Issue by lxuechen** [HazyResearch/flash-attention#144]
Hi, 

I'm opening this issue in light of this comment [here](https://github.com/HazyResearch/flash-attention/tree/main/csrc/layer_norm).

**Comment by tridao** [comment]
I've just added support for dimension up to 8192. Does that work for your use case?

**Comment by lxuechen** [comment]
that should just be sufficient to fine-tune 65b llama. thanks for the great work!
