### ISSUE TITLE
is S = QK^T stored in shared memory?

### ISSUE THREAD

**Issue by YichengDWu** [HazyResearch/flash-attention#149]
Hi,

Thanks for your great work. I have been trying to understand the implementation in detail. One thing confuses me it that in line 10, Algorithm 1, S=QK^T is computed on chip, does it mean S is stored in shared memory?

**Comment by tridao** [comment]
In our implementation S stays in registers. We don't write it to shared memory.

**Comment by YichengDWu** [comment]
Thanks for the clarification! I was confusing SRAM with shared memory. Dose it mean O is also stored in registers?

**Comment by tridao** [comment]
SRAM could mean shared memory or registers. O could also stay in registers (that's how it is in the Triton [implementation](https://github.com/HazyResearch/flash-attention/blob/d6fc86057305cc15d91f21221acc78a6bc1d672d/flash_attn/flash_attn_triton.py#L110)). It could also be written down to shared memory (in the current CUDA implementation). The choice is usually based on how easy it is to implement.

**Comment by YichengDWu** [comment]
It really helps me understand the implementation, thanks again for your great work!
