### ISSUE TITLE
Speed optimization for batch size 1 + seqlen 4k

### ISSUE THREAD

**Issue by terrychenism** [HazyResearch/flash-attention#15]
Hi Thanks for your great work! I tried flash_attn on the following setting, and found the speed is 2x slower than pytorch, any plan to optimize it? Thanks! 
Batch size 1
Head dimension 64
12 attention heads
seq lens 4096

**Comment by tridao** [comment]
Thanks for trying our code!
We've been focusing on larger batch size (e.g. 8, 16, etc.).
The small batch size case is interesting for inference, which we're looking into next.
Are you using it for inference or training? Would love to understand your use case more.

More details: we parallelize the work across (batch size x number of heads), so if this number is small (1 x 12 = 12 in your case), there's not enough parallel work. Ideally one would parallelize across (batch size x number of heads x query sequence length), at least for the forward pass.

**Comment by ptillet** [comment]
FWIW the Triton implementation there https://github.com/openai/triton/blob/master/python/tutorials/06-fused-attention.py does parallelize across (batch size x number of heads x query sequence length) and doesn't really suffer from low small-batch performance there as a result

**Comment by tridao** [comment]
Thanks Phil, the Triton fwd implementation looks really clean!

**Comment by ptillet** [comment]
Haha thanks :) We will open-source the backward pass in a few days too. It will have pretty poor small-batch performance though :D
