### ISSUE TITLE
pip install takes 10+ minutes on zen2 epyc

### ISSUE THREAD

**Issue by diegomontoya** [HazyResearch/flash-attention#150]
I stopped counting the minutes. May have been 15-20+. 

Is there any reason why this library takes such a long time to build? 

env
```
Ubuntu 22.04
Cuda 11.8
Ram: 128GB
Cpu:  Epyc 7252
```

```
apt install cuda-libraries-dev-11-8
pip install flash-attn
```

Is this normal? Or is this limitation of pip install where compilation is single threaded?

**Comment by tridao** [comment]
It usually takes 4-5 mins to compile for me.
There's a lot of templating for max perf, so compilation can be slow.
We use `ninja` to parallelize the compilation. It usually comes with PyTorch. Can you make sure that `ninja` is available (try `ninja --version`)? And check that multiple CPU cores are being used during compilation (e.g. with `htop`).

I usually use the Nvidia's Pytorch docker [image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) for my environment.

**Comment by diegomontoya** [comment]
@tridao  It was only use 1 core and I have pytorch 2.1 nightly installed on miniconda and ninja is not part of the depdency/bundle.  

Confirmed compile massive slow-down fixed with manual ```pip install ninja```. 

Perhaps flash-attn needs to add ninja as dependency since it's compilation demands is tremendous?

**Comment by ZJLi2013** [comment]
observed long install/build time(20+mins more), with `pip install flash-attn --no-build-isolation` , with NGC Pytorch Image on RTX A6K.  or it's suggested to build from source ?

**Comment by tridao** [comment]
@ZJLi2013 Did you have `ninja` installed as suggested in the README?
