### ISSUE TITLE
Looking for Guidance to use flash-attention

### ISSUE THREAD

**Issue by liuxing007** [HazyResearch/flash-attention#151]
Thanks so much for share flash-attention!
When I use flash-attention in VIT as follows:

  x = x + self.drop_path(self.attn(self.norm1(x), vis=vis))
  x = x + self.drop_path(self.mlp(self.norm2(x)))
------------->
  x = x + self.drop_path(self.flash_mha(self.norm1(x).cuda().half())[0])
  x = x + self.drop_path(self.mlp(self.norm2(x)))

It turns out that the calculated Loss is NaN. Looking for guidance! Thanks!

**Comment by tridao** [comment]
I don't understand why you're calling `self.attn` and `self.flash_mha` differently (e.g., with `.cuda().half()`, and no `vis=vis`).
Is the baseline ViT trained in fp32 and now you're just doing the attention in fp16?
If that's the case, you can try training baseline ViT in mixed precision first to see if there's NaN. Then you can swap in FlashAttention. If the baseline ViT with mixed precision gets NaN, then it's an issue of mixed precision (though many has successfully trained ViT with mixed precision).

You can print out the output of `self.attn` and `self.flash_mha` for the same output to make sure they're close (depending on inputs, numerical difference could be on the order of 1e-2. 

We also have an implementation of ViT [here](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/models/vit.py).

**Comment by liuxing007** [comment]
Thanks!
