### ISSUE TITLE
Training example using "ParallelFusedMLP" and "ParallelMHA" with 8cards.

### ISSUE THREAD

**Issue by nbcc** [HazyResearch/flash-attention#153]
Is tensor parallelism being considered for this project? Any examples of training? 

Expect the combination of ZeroRedundancyOptimizer to work.

**Comment by tridao** [comment]
We have some internal training runs that use those for tensor parallel. You can also use Megatron-LM if you want tensor parallel. And PyTorch 2.0 has an experimental [implementation](https://pytorch.org/docs/stable/distributed.tensor.parallel.html) of tensor parallel now.

**Comment by nbcc** [comment]
> We have some internal training runs that use those for tensor parallel. We have a [test](https://github.com/HazyResearch/flash-attention/blob/d6fc86057305cc15d91f21221acc78a6bc1d672d/tests/models/test_gpt_parallel.py#L2) showing how to construct a GPT model with tensor parallel and perform a forward and backward pass. It doesn't have the full training code though.
> 
> You can use Megatron-LM if you want tensor parallel. And PyTorch 2.0 has an experimental [implementation](https://pytorch.org/docs/stable/distributed.tensor.parallel.html) of tensor parallel now.

thanks, it's helpful!
