### ISSUE TITLE
Q: Release schedule?

### ISSUE THREAD

**Issue by ksivaman** [HazyResearch/flash-attention#156]
1. What's the release schedule for `flash-attn`? And when is the version number bumped?
2. When will the pip wheels be available for current `main` branch (in PyPI)?

**Comment by tridao** [comment]
1. We don't have a fixed release schedule, just when there'are enough changes & when I have time. Let me know if bumping the version number is helpful for you.
2. PyPI would be updated when we update the version number. We don't have pre-built wheels yet (something I hope to have at some point, but I haven't had the bandwidth to figure out compilation for different version of CUDA and PyTorch).

**Comment by ksivaman** [comment]
Yes, bumping the version would be useful since we would like to use features that are currently in main ([1](https://github.com/HazyResearch/flash-attention/pull/147), [2](https://github.com/HazyResearch/flash-attention/commit/dc08ea1c33afca500a3d4ada907608f7815a11d9), [3](https://github.com/HazyResearch/flash-attention/commit/1b18f1b7a133c20904c096b8b222a0916e1b3d37)). We would then be able to get it directly via pip and conveniently check for `v0.2.9` for our use case. @tridao

**Comment by tridao** [comment]
I've just released version `1.0.0`.
