### ISSUE TITLE
fatal error: cusolverDn.h: No such file or directory

### ISSUE THREAD

**Issue by Godofnothing** [HazyResearch/flash-attention#157]
Installation of flash-attention crashes due to the following message:
```
In file included from csrc/flash_attn/fmha_api.cpp:30:
      /nfs/scistore14/alistgrp/dkuznede/miniconda3/envs/llm/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
         10 | #include <cusolverDn.h>
            |          ^~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> flash-attn
```

**Environment**

I was attempting to install `flash_attention` in fresh conda environment created as follows:
```
conda create -y -n llm python=3.9 pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
```

CUDA version and pytorch version should satisfy the requirements. How can one resolve this problem?

**Comment by Godofnothing** [comment]
The solution was to load system version of CUDA, similarly to this [case](https://github.com/microsoft/DeepSpeed/issues/2684).

**Comment by AibibulaAtawula** [comment]
did u fix the problem?

**Comment by Godofnothing** [comment]
@AibibulaAtawula  yes - I did something like `module load cuda-11.6`

**Comment by AibibulaAtawula** [comment]
Thank you for your useful method. Which version did you use for it ?

**Comment by AibibulaAtawula** [comment]
@Godofnothing Thank you for your useful method. Which version did you use for it ?

**Comment by Godofnothing** [comment]
@AibibulaAtawula  do you mean version of ffcv?

**Comment by YeSho-cpp** [comment]
> @AibibulaAtawula yes - I did something like `module load cuda-11.6` (i.e the one of the CUDA versions availables on the cluster). On a local machine something like `export PATH=/usr/local/cuda/bin:$PATH` should help (the path to /usr/local/cuda/bin may be different). 是的-我做了类似 `module load cuda-11.6` 的事情（即集群上可用的CUDA版本之一）。在本地机器上，类似 `export PATH=/usr/local/cuda/bin:$PATH` 的东西应该会有帮助（到/usr/local/cuda/bin的路径可能不同）。

Hello, I have the same problem, export PATH=/usr/local/cuda/bin:$PATH，I want to ask how to find my cuda dir。
