### ISSUE TITLE
Regarding attention weights 

### ISSUE THREAD

**Issue by netw0rkf10w** [HazyResearch/flash-attention#159]
Hello,

It seems to me that flash attention always returns `None` as attention weights: https://github.com/HazyResearch/flash-attention/blob/d478eeec8f16c7939c54e4617dbd36f59b8eeed7/flash_attn/flash_attention.py#L71

Is there a reason why the weights cannot be returned? 

Thanks!

**Comment by tridao** [comment]
Yes, because the attention weights have size N x N, where N is the sequence length. FlashAttention aims to reduce memory reads/writes, so it does not materialize the attention weights.
