### ISSUE TITLE
Sequence Parallelism with Flash Attention

### ISSUE THREAD

**Issue by conceptofmind** [HazyResearch/flash-attention#162]
Hello!

I was wondering if you had done any previous testing with Flash Attention and Apex's sequence parallelism? Do you think there are potentially any incompatibility issues? 

Any input would be greatly appreciated.

Thank you,

Enrico

**Comment by tridao** [comment]
I think it should just work. We have internal runs that use tensor parallel, sequence parallel and FlashAttention, and they work fine.

**Comment by conceptofmind** [comment]
> I think it should just work. We have internal runs that use tensor parallel, sequence parallel and FlashAttention, and they work fine.

I greatly appreciate the input. Very helpful as always!

Thank you,

Enrico
