### ISSUE TITLE
Why can rotary embeddings not be used with cu_seqlen ?

### ISSUE THREAD

**Issue by RuABraun** [HazyResearch/flash-attention#177]
These seem like orthogonal features to me?

[Code link](https://github.com/HazyResearch/flash-attention/blob/96d10f654527cc82c81022e16f77a8d9564f7eba/flash_attn/modules/mha.py#L451)

**Comment by tridao** [comment]
Yes, they're orthogonal.
cu_seqlen is for cases where sequences in the same batch have different lengths, and we remove all the padding tokens and only store the regular tokens (e.g. BERT training).
To apply rotary embedding it'll take a bit more work to figure out the right indices. It's not necessarily hard, but I just never implemented it.
If you play with it and figure out something, let me know!

**Comment by RuABraun** [comment]
Sorry I don't understand. Orthogonal to me means unrelated, meaning one can toggle them (cu_seqlen / rotary) any way one wants without affecting the other.

> To apply rotary embedding it'll take a bit more work to figure out the right indices. It's not necessarily hard, but I just never implemented it.

But rotary embeddings are applied before the flash attention kernel, so why should that matter for whether or not the kernel operates on sequences of different length (by ignoring padding tokens or not)?

**Comment by tridao** [comment]
Let's say we have 2 sequences [A B <pad>] and [C D E] in the same batch.
Normally we would store them as [[A B <pad>], [C D E]].
If cu_seqlen is passed, we instead expect the input to be [A B C D E], with cu_seqlen = [0, 2, 5] (indicating that there are 2 sequences, one from index 0 to 2 and one from index 2 to 5).
If we want to apply rotary, the implementation has to be aware that [A B C D E] consists of 2 sequences, one of length 2 and one of length 3.
That's the more complicated indexing that I mentioned, and that is not implemented right now.

**Comment by RuABraun** [comment]
Ah! Ok I think I understand. Thank you so much for taking the time to explain!

**Comment by RuABraun** [comment]
have a follow up question @tridao 

What if I apply rotary to [[A B pad], [C D E]], and then convert it to [A B C D E], with cu_seqlen = [0, 2, 5], and then use that with flash attention? wouldnt that work?

**Comment by tridao** [comment]
Yes that would work. However, we'd need to convert between the "padded" and "unpadded" formats for each layer.
I think the more efficient way is to implement a version of rotary that can deal with "unpadded" format directly. It might not be that hard, we just have to adjust the indices in the rotary implementation.

**Comment by RuABraun** [comment]
Right right! Makes sense, thank you! :)

I might take a look at that in the future we'll see

**Comment by zanussbaum** [comment]
Just to double check that I understand the code correctly, this has been implemented here: https://github.com/Dao-AILab/flash-attention/commit/b28ec236df49cb57c213a9a4f29beb727adbf65b
correct?
