### ISSUE TITLE
Make a CPU version so computers without Nvidia card can run

### ISSUE THREAD

**Issue by by321** [HazyResearch/flash-attention#185]
Can you make a CPU version for computers without Nvidia cards ?

**Comment by tridao** [comment]
No, we only focus on GPUs.

**Comment by lms-mt** [comment]
> Can you make a CPU version for computers without Nvidia cards ?

FlashAttention is A trade-off between Flops and Mem-accesses. CPU cache/mem hierarchy is something different with GPU. I think Flash is shared-mem/register intensive, seems not ok to implement in CPU.
