### ISSUE TITLE
Support head dim 128 [could reuse existing code]

### ISSUE THREAD

**Issue by justheuristic** [HazyResearch/flash-attention#2]
**Context:** One great use case for flash attention would be large language models like GPT3, GPT-J, OPT or BLOOM.
However, all these language models use 128-dimensional heads. The current code only supports head dim 16,32,64, but you include 128d in your roadmap.

Another project on FMHA for long sequences found that even with head dimension 128, it was still possible to accelerate forward pass and significantly reduce memory usage, although backward pass would end up taking longer.

You can find their writeup at https://gist.github.com/krunt/72197074816dfe4035fcd9413e4afb22 ("Implementation" and "Evaluation") The 128d implementation is rudimentary: they just load two separate 64d vectors and add up results (for dot).
The backward pass is a bit slower in their implementation, but it may be worth it in some cases due to dramatic memory savings.

[The figure below is not mine, i copy-pasted it from the above gist, authors: @krunt @timDettmers ]
![image](https://user-images.githubusercontent.com/3491902/171168021-e2bc152e-db18-477d-b48d-bf763ca4556d.png)

**Comment by tridao** [comment]
So great to see we're thinking in the same direction!

Yes, we do plan to support head dimension 128.
Conceptually it's the same algorithm, but getting the maximum efficiency of shared memory reads/writes is a bit tricky with dimension 128.
I'm planning to refactor the code to use Cutlass first, and that should make it easier to support head dim 128. Hopefully this will be done in 2-4 weeks.

**Comment by tridao** [comment]
Head dimension 128 is now supported.
