### ISSUE TITLE
The installation process always freezes after execution.

### ISSUE THREAD

**Issue by Minxiangliu** [HazyResearch/flash-attention#215]
After executing the installation command, the result always freezes. Do you have any thoughts or suggestions on this?

Environment:
GPU: A100
System: Ubuntu18.04 and in Docker miniconda environment
pytorch: 1.13.1+cu116
CUDA: 11.6
![image](https://github.com/HazyResearch/flash-attention/assets/30144428/f6021b9d-5694-4e39-abad-ce5b7c8ed4bf)
Nvidia driver:
![image](https://github.com/HazyResearch/flash-attention/assets/30144428/c4fddff1-87b2-4b2e-9d51-1d77d34d8bfa)

I tried two methods, but neither of them worked.
Results 1:
`pip install flash-attn`
![image](https://github.com/HazyResearch/flash-attention/assets/30144428/56d4a39d-49ab-4591-b0ec-4b4802eb4b70)

Results 2:
`python -m pip install .`
![image](https://github.com/HazyResearch/flash-attention/assets/30144428/a45ffeb3-b74c-49c9-ae42-5c01689ecca0)

**Comment by tridao** [comment]
Compiling can take a long time if you don't have `ninja` to parallelize the build. I've just added `ninja` to the build requirements (I thought it usually comes with Pytorch).
You should check that multiple CPU cores are being used for compilation (e.g. with `htop`).
