### ISSUE TITLE
Cuda 12.1 is not supported.

### ISSUE THREAD

**Issue by larawehbe** [HazyResearch/flash-attention#219]
Hello 
In the main docs page, it states that requirements are:
Cuda: version 11.4 and above
But, it cannot be compiled with cuda 12, where it keeps on raising errors 
**RuntimeError:The detected CUDA version (12.1) mismatches the version that was used to compile PyTorch (11.7).**

**Comment by tridao** [comment]
CUDA 12.1 is supported. As the error mentioned, you just need Pytorch to be compiled with the same CUDA version.
If your Pytorch was compiled with CUDA 11.7, then you want to use the same version of nvcc to compile FlashAttention.

I use the Nvidia pytorch docker [image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) that has Pytorch compiled with CUDA 12.1 and installing works fine.

**Comment by vince62s** [comment]
this error appears even if you install torch nightly with cuda12.1

**Comment by tridao** [comment]
> torch.__version__  = 2.0.1+cu117

The installation script detects torch compiled with CUDA 11.7.
You can try printing out `torch.version.cuda`.

**Comment by vince62s** [comment]
I think I found why:
doing: `python -m pip install .` will whatever download the default torch wheel (ie: 2.0.1 + cu117 at the moment) from the repo which means it will never detect the local install 12.1
I am going to try python setup.py instead

**Comment by gugarosa** [comment]
> I think I found why: doing: `python -m pip install .` will whatever download the default torch wheel (ie: 2.0.1 + cu117 at the moment) from the repo which means it will never detect the local install 12.1 I am going to try python setup.py instead
> 
> EDIT: this is it. `python setup.py install` solves it

Thanks so much @vince62s! You are a lifesaver, I have spent some painful hours on this.

**Comment by vince62s** [comment]
likewise I spent 2 days to solve this for Tranformerengine installation on conda env.
check this: https://github.com/NVIDIA/TransformerEngine/issues/15 in the end.

**Comment by larawehbe** [comment]
Thanks Guys
I fixed the issue by downgrading to Cuda 11.8 as all other solutions didnt work on my end
Downgrading Cuda was straight forward, fast and works gently

**Comment by dlwh** [comment]
Based on this:

> EDIT: this is it. python setup.py install solves it

@tridao what do you think about updating the readme for installing from source?

**Comment by tridao** [comment]
> Based on this:
> 
> > EDIT: this is it. python setup.py install solves it
> 
> @tridao what do you think about updating the readme for installing from source?

Sure, it's done.
Tbh I'm not sure of the difference between the two ways.

**Comment by dlwh** [comment]
it seems that `pip install` tries to grab a pypi package first instead of relying on the cuda-installed version. I dunno why it's different, but i ran into this same issue.

**Comment by rpeys** [comment]
> If your Pytorch was compiled with CUDA 11.7, then you want to use the same version of nvcc to compile FlashAttention.

@tridao do you have a suggestion of how I can tell the system to use nvcc=11.7 (actually, 11.8 in my case, but same idea) when compiling flash attention? 

I have the same issue as OP: I have NVIDIA drivers for cuda 12.2, but installed torch using pip which only supports cuda<=11.8. Whether I install using `pip install "flash-attn<1.0.5"` or clone the repo and then run `python setup.py install`, I get the same error message `RuntimeError:
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.8). Please make sure to use the same CUDA versions.`.

**Comment by tridao** [comment]
Newer version of FlashAttention has pre-built wheels that will be automatically downloaded.
