### ISSUE TITLE
(Question) FMHA in FasterTransformers vs. FlashAttention

### ISSUE THREAD

**Issue by cadedaniel** [HazyResearch/flash-attention#220]
Hi, thanks for the great work!

I'm comparing performance of different inference engines and see that FasterTransformers has "FMHA" kernels (they call it fused multi-head attention). Is that the same as FlashAttention? I see from https://github.com/HazyResearch/flash-attention/issues/1 that y'all started with APEX FMHA, so maybe it is the case..

Is there a benchmark you suggest that will show a performance difference with / without FlashAttention during inference time?

Thanks!

**Comment by tridao** [comment]
We described the differences in Appendix E4 of the [paper](https://arxiv.org/abs/2205.14135), with benchmark numbers.
In short, FMHA is tailored to BERT (only support seqlen <= 512, headdim <= 64).
I believe if you're doing generation with GPT-style models in FasterTransformers, it uses FlashAttention for the prompt processing stage.

**Comment by cadedaniel** [comment]
Thanks @tridao !
