### ISSUE TITLE
Multi-query with flash-attetion

### ISSUE THREAD

**Issue by dongluw** [HazyResearch/flash-attention#227]
Do we support multi-query attention? (i.e. one head for KV and multiple heads for Q [as in this paper](https://arxiv.org/abs/1911.02150))

I noticed the [single_query_attention](https://github.com/HazyResearch/flash-attention/blob/40a25c8ee7465cf547b929cfa2937034e37bfce9/csrc/ft_attention/ft_attention.cpp#L102) method, wondering if I can do multi-query attention in a similar fashion?

**Comment by tridao** [comment]
Yes, I think so (though I've never tried that in C++, I usually call it from Python).

**Comment by dongluw** [comment]
Good to know that 😄 thank you!
