### ISSUE TITLE
about Return_sofmax as true and mask

### ISSUE THREAD

**Issue by lw921014** [HazyResearch/flash-attention#23]
hi, I have read your code and feel it is truly a greate job! I have some small quetiosn as following

1. in here [https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/gmem_tile.h#L380](url), if we want to save our softmax result(I mean set Return_sofmax as true), I found that for each thread, we get 16 ele, but here why we only save 8 ele into global mem? My parameter is head num = 12, head dim = 32, max_seq_len = 49.

2. about mask. I am confused for mask setting in [here](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/mask.h#L51). What is the mem layout for the mask? If I try to use a mask from global mem, How should I load data by each thread and then how to mask the q*k result correctly? here is my code for mask loading from global mem. Do you think it works?

`template<
    typename Cta_tile,
    int BYTES_PER_ELEMENT = 2
>
struct __align__(32) Gmem_tile_mask  {
    // Mask shape: [1, mWins, 1, seqlen, seqlen]

    static_assert(BYTES_PER_ELEMENT == 2);

    // The mma tile.
    using Mma_tile = fmha::Hmma_tile<Cta_tile>;

    // The size of each element.
    // static constexpr int BYTES_PER_ELEMENT = 2;
    // The size of each LDG.
    static constexpr int BYTES_PER_LDG = BYTES_PER_ELEMENT * 8;
    static constexpr int COLS = Cta_tile::K;
    // The size of a row in bytes.
    static constexpr int BYTES_PER_ROW = COLS * BYTES_PER_ELEMENT;

    // The number of threads to load a "row" of the matrix.
    static constexpr int THREADS_PER_ROW = BYTES_PER_ROW / BYTES_PER_LDG;
    // The number of "rows" load per iteration of the loop.
    static constexpr int ROWS = Cta_tile::M;
    // The number of "rows" stored per iteration of the loop.
    static constexpr int ROWS_PER_LOOP = ROWS <= 64 ? ROWS : (int)Mma_tile::M_PER_MMA_PER_CTA;
    // The number of outter loop for the stores.
    static constexpr int LOOPS = ROWS / ROWS_PER_LOOP;

    // The number of "rows" load per load.
    static constexpr int ROWS_PER_LDG = Cta_tile::THREADS_PER_CTA / THREADS_PER_ROW;
    // Do we have to guard against partial writes/reads.
    static constexpr bool HAS_INCOMPLETE_STG = Cta_tile::M % ROWS_PER_LDG != 0;
    // The number of LDGS needed to store a chunk of the Q matrix.
    static constexpr int LDGS_PER_LOOP = DivUpConstexpr(ROWS_PER_LOOP, ROWS_PER_LDG);
    // The number of LDGS needed to store a chunk of the Q matrix in total.
    static constexpr int LDGS = LDGS_PER_LOOP * LOOPS;

    // Ctor.
    template<typename Params, typename BInfo>
    inline __device__ Gmem_tile_mask(const Params &params, const BInfo &binfo, const int tidx)
        : row_stride_in_bytes(64 * BYTES_PER_ELEMENT)
        , actual_seqlen_q(binfo.actual_seqlen_q)
        , actual_seqlen_k(binfo.actual_seqlen_k)
        , tidx_(tidx) {
       
        is_none_ = params.attn_mask_ptr == nullptr;
        if (!is_none_) { 
                int bidb = binfo.bidb; // batch id
                // for bid offset, cause the input dim is [1, mWins, 1, N, N]
                // mWins the numbers of windows, N is the seq len
                // the dim of q*kt is  [B / mWins, mWins, num, N, N]

                uint64_t bidb_offset = bidb % params.attn_mask_batch; 
                ptr_ = reinterpret_cast<char *>(params.attn_mask_ptr) + 
                        (uint64_t)bidb_offset * actual_seqlen_q * actual_seqlen_k * BYTES_PER_ELEMENT;

                // Compute the position in the sequence (within the CTA for the moment).
                int row = tidx / THREADS_PER_ROW;
                // Compute the position of the thread in the row.
                int col = tidx % THREADS_PER_ROW;

                // The row offset in the batched GEMM.
                // int64_t row_offset = (int64_t)row * row_stride_in_bytes + binfo.bidx * BYTES_PER_ROW;
                uint32_t row_offset = (uint32_t)(row * row_stride_in_bytes);
                // Assemble the final pointer.
                ptr_ += row_offset + col * BYTES_PER_LDG;
        }
    }
    inline __device__ bool is_none() {
        return is_none_;    
    }	
    inline __device__ void load() {
        if (is_none_) { return;}

        int row_ = tidx_ / THREADS_PER_ROW;
        int col = tidx_ % THREADS_PER_ROW;
        const void *ptrs[LDGS];
        uint32_t preds[LDGS];
        #pragma unroll
        for( int ii = 0; ii < LDGS; ++ii ) {
            ptrs[ii] = ptr_ + (uint32_t)ii * ROWS_PER_LDG * row_stride_in_bytes;
            // preds[ii] = ((row_ + ii * ROWS_PER_LDG) < min(ROWS, actual_seqlen_q) && col < min(COLS, actual_seqlen_k));
            preds[ii] = ((row_ + ii * ROWS_PER_LDG) < min(ROWS, actual_seqlen_q) && ((col * BYTES_PER_LDG / BYTES_PER_ELEMENT) < min(COLS, actual_seqlen_k)));
            // fetch_[ii] = make_uint4(1, 1, 1, 1);
            fetch_[ii] = make_uint4(0, 0, 0, 0);
        }

        // not packing predicates removes restrictions (e.g. FP16 384, 4 warps)
        Ldg_functor<uint4, LDGS> fct(fetch_, ptrs);
        #pragma unroll
        for( int ii = 0; ii < LDGS; ++ii ) {
            fct.load(ii, preds[ii]);
        }
    }

    inline __device__ void move(const int steps = 1) {
        if (is_none_) {return ;}
        // row_ += ROWS * steps;
        // ptr_ += (int64_t)ROWS * row_stride_in_bytes * steps;
        ptr_ += (uint32_t)ROWS * row_stride_in_bytes * steps;
        this->actual_seqlen_q -= ROWS * steps;
    }

    uint4 fetch_[LDGS];
    // The stride between rows for the attn mask.
    // int64_t row_stride_in_bytes;
    const uint32_t row_stride_in_bytes;
    // The pointer.
    char *ptr_;
    int actual_seqlen_q;
    int actual_seqlen_k;
    // const Gmem_tile tile_;
    const int tidx_;
    bool is_none_; // processs when atten_mask is None
};
`

here is how to use mask 
`    inline __device__ bool is_valid(const int mi, const int ni, const int ii, const int jj) const {
        if (mask_tile->is_none()) {
            return true;
        }

        // // ii and jj iterate over the 2x4 fragment
        // // const int current_col = (Is_causal ? loop_step_idx * Cta_tile::N : 0) + ni * Mma_tile::N_PER_MMA_PER_CTA + col + (jj & 2) * 4 + (jj & 1);
        // const int current_col = ni * Mma_tile::N_PER_MMA_PER_CTA + col + (jj & 2) * 4 + (jj & 1);
        // const int current_row = row_offset + ii * 8;
        // const bool col_valid = current_col < actual_seqlen_k;
        // // const bool col_valid = (ni * Mma_tile::N_PER_MMA_PER_CTA + col + (jj & 2) * 4 + (jj & 1)) < actual_seqlen_k;
        // //&& (row + mi * Mma_tile::M_PER_MMA_PER_CTA + ii * 8) < actual_seqlen_k;
        // // if ((threadIdx.x == 0) && (blockIdx.x == 0) && (blockIdx.y == 0)) {
        // //     printf("current_col=%d, current_row=%d, actual_seqlen_k=%d, col_valid=%d, all_valid=%d\n", current_col, current_row, actual_seqlen_k, col_valid, all_valid);
        // // }
        // // printf("Is_causal = %d, col_valid = %d, current_col = %d, current_row = %d, loop_step_idx = %d\n",
        // //             Is_causal, col_valid, current_col, current_row, loop_step_idx);
        // // return Is_causal ? col_valid && (current_col + loop_step_idx * Cta_tile::N <= current_row) : col_valid;

        int uint4_offset = mi * 2 + ni;
// #ifdef DEBUG_USING_CU
//         if (blockIdx.x == 0 && blockIdx.y == 0) {
//             printf("mi = %d, ni = %d, ii = %d, jj = %d, LDGS = %d, uint4_offset = %d\n",  
//                 mi, ni, ii, jj, mask_tile->LDGS, uint4_offset);
//         }
// #endif
        // if (mi != 0 || ni > 1) {
        //     return false;
        // }

        cutlass::half_t value = *(reinterpret_cast<cutlass::half_t*>(&mask_tile->fetch_[mi * 2 + ii]) + ni * 4 + jj);
        bool valid = true;
        valid = float(value) >= 0.0f;
        printf("blockIdx.x = %d, blockIdx.y = %d, threadIdx.x = %d, threadIdx.y = %d, mi = %d, ni = %d, ii = %d, jj = %d, value = %f, valid = %d\n",
                blockIdx.x, blockIdx.y, threadIdx.x, threadIdx.y, mi, ni, ii, jj, float(value), valid);
// #ifdef DEBUG_USING_CU
//         if (blockIdx.x == 0 && blockIdx.y == 0) {
//             printf("mi = %d, ni = %d, ii = %d, jj = %d, value = %f, valid = %d, LDGS = %d\n",
//                     mi, ni, ii, jj, float(value), valid, mask_tile->LDGS);
//         }
// #endif

        return valid;
    }`

**Comment by tridao** [comment]
1. I think we're writing 8 elements of type uint32 because it corresponds to 16 elements of type float16.
2. I've talked a bit about the layout in #24.
The Python code converting the internal layout to standard layout is [here](https://github.com/HazyResearch/flash-attention/blob/2ed471ecc450801cbe30be2169936a7fe69058c4/tests/test_flash_attn.py#L232). That could be helpful to understand the layout as well.
