### ISSUE TITLE
Please provide Dockerfile with working installation

### ISSUE THREAD

**Issue by ivsanro1** [HazyResearch/flash-attention#230]
There are a lot of issues with problems with installation, and I'm facing also a lot of problems installing this library.

I think it would be good to have a Dockerfile with installation and a minimal test to show at least some exact CUDA, torch, python versions in which it can be installed.

Thank you.

**Comment by tridao** [comment]
Good idea. We recommend the
[Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)
container from Nvidia, which has all the required tools to install FlashAttention.

I've added this to the README.
