### ISSUE TITLE
test_flash_attn fails at T4

### ISSUE THREAD

**Issue by stephen-youn** [HazyResearch/flash-attention#235]
Hi All,
I gave it a try of installing the flash_attn and run it with T4 but got the following error.
the env i have is ubuntu20.04, torch112cuda116 with T4

```
    import flash_attn_cuda
E   ImportError: /home/dsuser/.local/lib/python3.8/site-packages/flash_attn_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
```

**Comment by tridao** [comment]
It probably has to do with cuda version / gcc version.
We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by tridao** [comment]
Also can you try `pip install flash-attn==1.0.4`? 
We changed something in the installation process recently (1.0.5) to accommodate conda, that might have lead to installation errors in other settings.

**Comment by stephen-youn** [comment]
changing the version to 1.0.4 made the test passes in T4

**Comment by tridao** [comment]
Thank you! Let me figure out the installation change between 1.0.4 and 1.0.5 today.

**Comment by richardwth** [comment]
I also came across a similar ImportError with 1.0.5. For 1.0.6, the error is

**Comment by bzip2** [comment]
> It probably has to do with cuda version / gcc version. We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

Hi, @tridao The Nvidia Pytorch container comes in many versions. It would be useful to people if you specify which version of flash-attn can be installed in which Pytorch container. Through trial and error, I was able to install v1.0.1 and v1.0.4 in the the 22.08 container (CUDA 11.7, PyTorch 1.13).
