### ISSUE TITLE
Head dim = 128 for inference only on sm8.6 GPUS

### ISSUE THREAD

**Issue by jd-unknown** [HazyResearch/flash-attention#244]
Hi! I read "Head dimensions that are multiples of 8, up to 128 (e.g., 8, 16, 24, ..., 128). Head dim > 64 backward requires A100 or H100." and understand due to l1 cache limitations, A100/H100 is required to train models with head_dim = 128.

My target Ampere GPUs only have 100kB shared memory size but I wonder if it's possible to configure to run with head_dim = 128 if i'm running inference only. Thanks !

**Comment by tridao** [comment]
Yes that's already supported.
