### ISSUE TITLE
Lack of Bfloat16 Support in BlockSparse, Known Issues?

### ISSUE THREAD

**Issue by kuizhiqing** [HazyResearch/flash-attention#247]
I have found that the bf16 is not supported in the blocksparse API. I attempted to implement bf16 support but failed due to accuracy issues. Is lack of bf16 support a known limitation in blocksparse, or are there other known issues I should be aware of? 

Thank you in advance for any information.

**Comment by tridao** [comment]
Yeah I don't think blocksparse supports bf16.

**Comment by kuizhiqing** [comment]
@tridao Thank you for your reply. Could you please provide more details about why bf16 support cannot be implemented in BlockSparse, or how we might overcome these barriers?

I'd really appreciate your help.

**Comment by tridao** [comment]
I just don't have bandwidth to support bf16.
