### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by zzningxp** [HazyResearch/flash-attention#249]
My environment is 
`Ubuntu 18.04, CUDA 11.7, torch 1.13, gcc-7, python 3.8(miniconda), 2080ti, NV-driver 515.43.04 `

I tried 
`pip install flash-attn=0.2.2 `
`pip install flash-attn=0.2.8 `
`pip install flash-attn `
`python setup.py install ` with many version

I encounter into the same ERROR type, the text is too long and I paste some of them below:
```
/opt/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/pybind11/pytypes.h:976:30:   required from ‘pybind11::str pybind11::str::format(Args&& ...) const [with Args = {pybind11::object&, pybind11::str}]’
/opt/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h:1643:79:   required from here
/opt/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/pybind11/cast.h:2229:45: error: no matching function for call to ‘collect_arguments(pybind11::object&, pybind11::str)’
     return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/pybind11/cast.h:2208:26: note: candidate: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...)
 simple_collector<policy> collect_arguments(Args &&...args) {
```

```
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
          subprocess.run(
        File "/opt/miniconda3/envs/py38/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:
```

I guess that ninja error is not the fault of ninja, it must be something wrong with the following augments after ninja. However, I don't know what and why.

**Comment by tridao** [comment]
I don't know either. 

We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by zzningxp** [comment]
I pull a docker (nvcr.io/nvidia/pytorch:19.03-py3) from [pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch).

But, when I launch the docker by command `docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:xx.xx-py3` as the introduction, I got: 
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: mount operation failed: /home/data/docker/docker-lib/overlay2/bb47d7506c4e60fb329c841a01129653e22e1531da44ed6fe631d2b1aee33d66/merged/proc/driver/nvidia/params/version/registry: no such file or directory\\\\n\\\"\"": unknown.`

Is there more detailed introductions?

**Comment by tridao** [comment]
Seems to be issue with docker and your setup. You can look up the documentation for the nvidia docker (idk if there is one). I use the latest version (pytorch:23.04-py3).

**Comment by zzningxp** [comment]
I delete the miniconda envs and start the whole process over again. And now it works.
Notice that this time I update gcc/g++ to gcc-9/g++-9. (I don't know whether or not it is the key problem)

I put the detailed commands here, as the introduction for others.
```
conda create -n py38f python=3.8
conda activate py38f
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
sudo apt install gcc-9 g++-9
sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
sudo ln -s /usr/bin/g++-9 /usr/bin/g++
pip install flash-attn==0.2.2
```
