### ISSUE TITLE
ModuleNotFoundError: No module named 'dropout_layer_norm' when trying to import flash_attn.ops.layer_norm

### ISSUE THREAD

**Issue by yizhouthu** [HazyResearch/flash-attention#250]
I am trying a VIT testcase on flash-attn, where I need to import flash_attn.ops.layer_norm.

https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/ops/layer_norm.py#L7

Here comes an ModuleNotFoundError.

**Comment by tridao** [comment]
You can install:
`cd csrc/layer_norm && python setup.py install`

**Comment by yizhouthu** [comment]
> You can install:
> `cd csrc/layer_norm && python setup.py install`

It works. Thanks.

**Comment by Hspix** [comment]
@tridao 
When ```cd csrc/layer_norm && pip install .```, is costs two days without ending and there are a dozens of ```cicc --c++17 --gnu_version=90400 --orig_src_file_name /flash-attention/cs...```. What's the reason of it?

**Comment by tridao** [comment]
Lots of templating, so it might take a while to compile (around 5 mins on a 64-core machine for me). You don't have to use it, just don't enable `fused_dropout_add_ln` (which defaults to False).

**Comment by Hspix** [comment]
But unavoidably, qwen-7b-chat advise to use ```csrc/layer_norm``` and ```csrc/rotary```. Will it download something when the installing under my poor Internet speed?

**Comment by tridao** [comment]
Idk what qwen chat is recommending, you can create an issue with them. You can ask if they have an option to run without `csrc/layernorm`.

**Comment by nichorians** [comment]
> [@tridao](https://github.com/tridao) When , is costs two days without ending and there are a dozens of processes. What's the reason of it?`cd csrc/layer_norm && pip install .``cicc --c++17 --gnu_version=90400 --orig_src_file_name /flash-attention/cs...`

I have encountered the same issue as you. Have you dealt with it?

**Comment by tridao** [comment]
`csrc/layer_norm` is no longer used, we recommend the triton version:
https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/ops/triton/layer_norm.py

**Comment by nichorians** [comment]
> `csrc/layer_norm` is no longer used, we recommend the triton version: https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/ops/triton/layer_norm.py

Thanks for your response.
