### ISSUE TITLE
compiling layer_norm never ending

### ISSUE THREAD

**Issue by luckyfish0826** [HazyResearch/flash-attention#268]
as captioned, processes are using CPU 100%, but the compiling just not ending. It stays at below message:

--------------------------------
Emitting ninja build file /home/notebook/data/personal/80342508/text-generation-inference-main/server/flash-attention/csrc/layer_norm/build/temp.linux-x86_64-cpython-39/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
--------------------------------

any one can give me a hint? Thanks!
My hardware is A100

**Comment by tridao** [comment]
With ninja it takes 4-5 mins to compile on a machine with 64 cores ( using the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia).

**Comment by luckyfish0826** [comment]
> With ninja it takes 4-5 mins to compile on a machine with 64 cores ( using the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia).

Thank you for your note, I'll try with this kind of container

**Comment by luckyfish0826** [comment]
yes, using the pytorch from NVIDA, it's a lot faster, maybe less than 20 mins.
