### ISSUE TITLE
Failed building wheel for flash-attn

### ISSUE THREAD

**Issue by caixun99** [HazyResearch/flash-attention#269]
creating build/lib.linux-x86_64-cpython-38/flash_attn/losses
      copying flash_attn/losses/cross_entropy_parallel.py -> build/lib.linux-x86_64-cpython-38/flash_attn/losses
      copying flash_attn/losses/__init__.py -> build/lib.linux-x86_64-cpython-38/flash_attn/losses
      copying flash_attn/losses/cross_entropy.py -> build/lib.linux-x86_64-cpython-38/flash_attn/losses
      copying flash_attn/losses/cross_entropy_apex.py -> build/lib.linux-x86_64-cpython-38/flash_attn/losses
      running build_ext
      /data/home/xuncai/anaconda3/envs/llm/lib/python3.8/site-packages/torch/utils/cpp_extension.py:387: UserWarning: The detected CUDA version (11.0) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /data/home/xuncai/anaconda3/envs/llm/lib/python3.8/site-packages/torch/utils/cpp_extension.py:397: UserWarning: There are no g++ version bounds defined for CUDA version 11.0
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'flash_attn_cuda' extension
      creating /tmp/pip-install-vtz3lk_i/flash-attn_38dfe6a6d0904a369d24c5ba53f9d63c/build/temp.linux-x86_64-cpython-38
      creating /tmp/pip-install-vtz3lk_i/flash-attn_38dfe6a6d0904a369d24c5ba53f9d63c/build/temp.linux-x86_64-cpython-38/csrc
      creating /tmp/pip-install-vtz3lk_i/flash-attn_38dfe6a6d0904a369d24c5ba53f9d63c/build/temp.linux-x86_64-cpython-38/csrc/flash_attn
      creating /tmp/pip-install-vtz3lk_i/flash-attn_38dfe6a6d0904a369d24c5ba53f9d63c/build/temp.linux-x86_64-cpython-38/csrc/flash_attn/src
      error: [Errno 8] Exec format error: 'c++'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects

**Comment by tridao** [comment]
Sounds like some mismatched CUDA version as mentioned in the warning (CUDA 11.0 vs 11.6).
We require CUDA 11.4 or later.
We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by millerh1** [comment]
Which Pytorch container? Is there a minimum version? I tried with 20.10 and it did not work

**Comment by tridao** [comment]
I usually use the newest one (e.g. 23.05). I think anything from 22.05 (when FlashAttention was released) should work.

**Comment by wduo** [comment]
I use nvcr.io/nvidia/pytorch:23.02-py3, still error.
