### ISSUE TITLE
Support for more pascal architecture GPUs?

### ISSUE THREAD

**Issue by chinoll** [HazyResearch/flash-attention#27]
Hi, Tri Tao,

Do you have plans to support more consumer-grade GPUs(e.g., 1080, 1070, 1060)?

**Comment by tridao** [comment]
We currently support Turing (e.g. RTX 2080) and Ampere (e.g. RTX 3080) GPUs. We rely on tensor cores for matrix multiplication, which older GPUs lack.

**Comment by mihdalal** [comment]
Do you support V100? (roadmap doesn't have it crossed out so I wanted to double check): [Jul 2022] Support SM70 GPUs (V100).

**Comment by tridao** [comment]
Not yet, that'll take some work. Hopefully in the near future.

**Comment by chinoll** [comment]
> We currently support Turing (e.g. RTX 2080) and Ampere (e.g. RTX 3080) GPUs. We rely on tensor cores for matrix multiplication, which older GPUs lack. You might be interested in the memory-efficient attention implemented by the xformers team (targeting fp32 instead of fp16), which I believe supports Pascal cards: [facebookresearch/xformers#267](https://github.com/facebookresearch/xformers/pull/267) [facebookresearch/xformers#281](https://github.com/facebookresearch/xformers/pull/281)

thanks

**Comment by TimJDix** [comment]
>  We rely on tensor cores for matrix multiplication, which older GPUs lack.

What about GPUs like the p40? It uses pascal architecture, but has more tensor cores than a 4090. Is it possible to do add support for this GPU?

**Comment by tridao** [comment]
> What about GPUs like the p40? It uses pascal architecture, but has more tensor cores than a 4090. Is it possible to do add support for this GPU?

I personally don't have plan to do that. We're mostly constrained by time.

**Comment by maifeeulasad** [comment]
Now, do we have support for RTX 1080 ti 11GB? I don't think so

**Comment by tridao** [comment]
No, RTX 1080 is not supported
