### ISSUE TITLE
Can't find doc/mma_smem_layout.xlsx

### ISSUE THREAD

**Issue by umiswing** [HazyResearch/flash-attention#281]
Hello! The comment in [smem_tile.h](https://github.com/HazyResearch/flash-attention/blob/9818f85fee29ac6b60c9214bce841f8109a18b1b/csrc/flash_attn/src/fmha/smem_tile.h#L127) mentions that the mapping of the thread to shared memory is displayed in doc/mma_smem_layout.xlsx. However, I am unable to locate this file. Would you be able to provide it?

**Comment by tridao** [comment]
This file `smem_tile.h` was adapted from [apex](https://github.com/NVIDIA/apex/blob/master/apex/contrib/csrc/fmha/src/fmha/smem_tile.h). Idk what that file refers to, my guess is that it's some internal Nvidia doc.

**Comment by umiswing** [comment]
@tridao thanks, you're right, it's not publicly available according to https://github.com/NVIDIA/apex/issues/1352 :( 
But this idea comes from https://github.com/NVIDIA/cutlass/blob/f6d42f2dd01779acfddf1b8db2b05fd30f49c5b3/media/docs/implicit_gemm_convolution.md#shared-memory-layouts . This is enough to understand the code.
