### ISSUE TITLE
llama rotary pos embedding

### ISSUE THREAD

**Issue by ftgreat** [HazyResearch/flash-attention#288]
As https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/models/llama.py#L118 says, rotary_emb_interleaved is set to true. While llama paper mentions Rotary Embeddings [GPTNeo]. 

Confused whether llama rotary_emb_interleaved will be set false or true. Thanks.

**Comment by tridao** [comment]
If you use the official weights from Meta, `interleaved` is True (you can see the Meta's implementation [here](https://github.com/facebookresearch/llama/blob/57b0eb62de0636e75af471e49e2f1862d908d9d8/llama/model.py#L63)).
If you use the weight conversion script from Huggingface (which permutes the indices [here](https://github.com/huggingface/transformers/blob/daccde143d646e4fec8d52cc870b8c7fd1d2581c/src/transformers/models/llama/convert_llama_weights_to_hf.py#L100)), `interleaved` is False.

We test our LLaMa implementation (loading Meta's weights) against Huggingface implementation (loading weights that has been converted) [here](https://github.com/HazyResearch/flash-attention/blob/main/tests/models/test_llama.py).
