### ISSUE TITLE
Question about `flash_attn_unpadded_func`

### ISSUE THREAD

**Issue by ksivaman** [HazyResearch/flash-attention#293]
In the `flash_attn_unpadded_func` API, in case `total_q` and `total_k` (as specified in the docstrings) are different, then what is the output dimension? The docstring says `(total, nheads, headdim)`, what's `total` here?

Edit: From some basic experiments, looks like it's just `total_q`?

**Comment by tridao** [comment]
Yes, it's just `total_q`. I'll update the doc.
