### ISSUE TITLE
Use case of block-sparse flash attention?

### ISSUE THREAD

**Issue by jamesharrisivi** [HazyResearch/flash-attention#294]
<img width="852" alt="Screenshot 2023-07-02 at 12 54 34" src="https://github.com/HazyResearch/flash-attention/assets/132676609/b7747696-8d83-4085-a588-d72a48d8ce14">

How do you decide the Mask matrix? i.e. where does it come from.

Am I right and this Is only to be used for specific models like BigBird and cannot naively be applied to most models.

**Comment by tridao** [comment]
The mask is decided beforehand, e.g. BigBird, Longformer, etc.
