### ISSUE TITLE
[implementation] Support turing GPUs

### ISSUE THREAD

**Issue by krunt** [HazyResearch/flash-attention#3]
We noticed you have turing (sm75) support in your roadmap.
We've investigated this issue in our concurrent project with @TimDettmers and @xtinkt
There are only two challenges for that:
- reduce block sizes to fit into smaller Turing shared memory
- different intrinsic calls for dimension k=8 (instead of k=16 mma versions on ampere)

You can find our fix for the latter here:  https://github.com/krunt/apex/commit/aed95f248e9925c356509e0354f3adddd28fa03f

**Comment by tridao** [comment]
Thanks for the pointers! Turing GPUs are now supported.
