### ISSUE TITLE
[QUESTION] Typo in the paper ?

### ISSUE THREAD

**Issue by DongqiShen** [HazyResearch/flash-attention#301]
Hi there,
     I am reading the paper and want to know the details of the algorithm. However, I encountered a problem while deriving the formula. It is on page 23, and I took a screenshot below.
<img width="1099" alt="Screenshot 2023-07-11 at 13 56 32" src="https://github.com/HazyResearch/flash-attention/assets/32640333/db4cc2ca-647a-4efa-abff-08d170fd0e44">
If I was right, the second $diag(\ell^{(j)})$ should be $diag(\ell^{(j)})^{-1}$, and then these two items gone to be disappear. 
Feel free to point out my mistake, I will be appreciated for that.
Thanks.

**Comment by tridao** [comment]
Yes that's right, there's a {-1} missing. Thanks for pointing that out.

**Comment by DongqiShen** [comment]
Thanks！
