### ISSUE TITLE
How many elements calculated by one thread?

### ISSUE THREAD

**Issue by robotcator** [HazyResearch/flash-attention#33]
Hi, @tridao  I have read your code and it is a great job! But I still have some small questions as follows, can you explain them in more detail?
As we declared here [grid size<b, h> and block size <Kernel_traits::THREADS>](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha_fprop_fp16_kernel.sm80.cu#L78), the input data shape is [totalsize, head, head_dim], how to divide the matrix into submatrix calculated in one thread.

**Comment by tridao** [comment]
Sure thing.
We split the attention computation into (batch_size * nheads) independent heads. Each CUDA threadblock of 128 / 256 threads will compute attention for one head.
All 128 / 256 threads need to coordinate for that one head (the work isn't independent).

**Comment by robotcator** [comment]
Thank you for your reply.  I found that the code [iteratives over the q matrix length in here](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha_fprop_kernel_1xN.h#L658) and [iterative over the k matrix length in here](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha_fprop_kernel_1xN.h#L666), I have a little bit hard to understand that the q, k, v which initialized in [here] (https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/gmem_tile.h#L75-L91), why we use thread index to cacluate row and col, so that we can locate the q matrix pointer.

**Comment by tridao** [comment]
That's right.
To get the q, k, v, we need to index into the array of shape [total_size, head, head_dim], using the cumulative sequence lengths.
[the inputs are already unpadded, i.e., the padding tokens are removed].

FasterTransformer has some [illustration](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/bert_guide.md#standard-bert-and-effective-fastertransformer) of this approach.

**Comment by robotcator** [comment]
Great illustrations for the padding of the sequence. But my confusion is in [there](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/gmem_tile.h#L77), how each CUDA thread block of 128 / 256 threads organized to compute the submatrix.

**Comment by robotcator** [comment]
@tridao thank you for the explanation, I figured out this problem now. 
close this issue.
