### ISSUE TITLE
Does it support `q` and `k` with distinct lengths (i.e. cross-attention)?

### ISSUE THREAD

**Issue by Karbo123** [HazyResearch/flash-attention#39]
First, many thanks to this great project, I really appreciate the great effort to make attention compute faster.

I have read the python API [here](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attention.py), and it only seems to allow `q` and `k`/`v` to have the same length, because the input param (i.e. `qkv` binds `q`, `k` and `v` together, which means within one batch, `q`, `k` and `v` must have the same length). But what if the `q` has length `len_q`, and the `k`/`v` has length `len_kv`, where `len_q != len_kv`. I mean, in this case, it allows the codes to work for cross-attention whose input tokens are from different sources.

Or is there any mistake I have made above?

Looking forward to the reply! Thank you very much.

**Comment by tridao** [comment]
We support cross attention where q and k/v don't have the same length. You'd want to call [this function](https://github.com/HazyResearch/flash-attention/blob/19d126102542086ba5dbaee07878220a24c58581/flash_attn/flash_attn_interface.py#L213).

The FlashAttention module is just a light wrapper to call into this interface, which then calls the CUDA code.
You'd need to write a FlashCrossAttention module.

**Comment by Karbo123** [comment]
Thank you! It's very helpful.
