### ISSUE TITLE
parallel execution of read/write operations (paper vs implementation)

### ISSUE THREAD

**Issue by pommedeterresautee** [HazyResearch/flash-attention#40]
In Algorithm 1 of *FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness*, the inner loop starts by loading from HBM in SRAM a tile from tensor `O` into `Oi`. It then do some ops and save `Oi` from SRAM into HBM tensor `O`. For each iteration of the outer loop, the inner loop do a full round and therefore there is a full read / write of `O` tensor.

If the outer loop (`j`) is executed serially, it should provide the correct result. 
But when we execute in parallel the outer loop, it seems that we would have concurrent access to `O` for both reading and writing.
Therefore, if we strictly follow the algorithm 1 and "just" parallelize the outer loop, the output should not be correct.

In the triton implementation, they have switched inner and outer loop, therefore they don't need to load `Oi`, they start with a zeroed one, do all computation and save to HBM the final result. Therefore they don't have any concurrent access issue on this variable.

Can you please clarify the way the parallelization is implemented in CUDA? Is there something missing in the description above which may explain why algorithm 1 would work in parallel?

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/1029874/187489685-2b9332fe-c61e-4f88-aee4-c4d87292721d.png">

**Comment by tridao** [comment]
That's a great observation!
The CUDA code implements the algorithm as written in the paper, we do not parallelize the outer loop.
Instead, we parallelize over the batch and nheads dimension (each threadblock computes 1 head). This is sufficient if batch * nheads is large enough (around >= 80) so we have enough parallel work for each threadblock to do.

One could also swap the order of the inner and outer loop (as done in Triton).

**Comment by pommedeterresautee** [comment]
Thank you it's very clear.

**Comment by ZhongYingMatrix** [comment]
> One could also swap the order of the inner and outer loops (as done in Triton).

Hi tridao, sorry for bothering you in a closed issue again. As Triton swaps the order of the loops,
ori:
```
for 1 ≤ 𝑗 ≤ 𝑇𝑐 do
    Load K𝑗, V𝑗 from HBM to on-chip SRAM.  
    for 1 ≤𝑖 ≤ 𝑇𝑟 do  
        Load Q𝑖, O𝑖 ,ℓ𝑖, 𝑚𝑖 from HBM to on-chip SRA  
```
swapped:
```
for 1 ≤𝑖 ≤ 𝑇𝑟 do
    for 1 ≤ 𝑗 ≤ 𝑇𝑐 do
        Load K𝑗, V𝑗 from HBM to on-chip SRAM.  
        Load Q𝑖, O𝑖 ,ℓ𝑖, 𝑚𝑖 from HBM to on-chip SRA  
```
It seems that the loading of K/V increases to 𝑇𝑟 times for the Triton version?

**Comment by tridao** [comment]
Yes, but now one only needs to load Q once (instead of T_c times) and one can keep the output O on SRAM instead of having to repeatedly writing to / reading from HBM.
Overall the HBM reads/writes will be around the same, but one version might be faster / easier to implement.

**Comment by ZhongYingMatrix** [comment]
Thanks for your reply~
so the Triton version exactly swaps
```c
// executed in parallel outside over the batch and nheads dimensions
for 1 ≤ 𝑗 ≤ 𝑇𝑐 do   // executed serially
    Load K𝑗, V𝑗 from HBM to on-chip SRAM.  
    for 1 ≤𝑖 ≤ 𝑇𝑟 do   // executed serially
        Load Q𝑖, O𝑖 ,ℓ𝑖, 𝑚𝑖 from HBM to on-chip SRA
        ...
        Write O𝑖 ,ℓ𝑖, 𝑚𝑖 to HBM
```
to
```c
for 1 ≤𝑖 ≤ 𝑇𝑟 do  // executed in parallel
    Load Q𝑖 from HBM to on-chip SRA
    Initialize O𝑖 ,ℓ𝑖, 𝑚𝑖 to on-chip SRAM
    for 1 ≤ 𝑗 ≤ 𝑇𝑐 do  // executed serially
        Load K𝑗, V𝑗 from HBM to on-chip SRAM
        ...
    Write O𝑖 to HBM
```
Do I understand it correctly?

**Comment by tridao** [comment]
Yes, that's right.

**Comment by tridao** [comment]
For reference, the CUDA implementation now parallelizes over the seqlen_q dimension (in addition to the batch and nheads dimension), in both the forward and backward pass. It significantly speeds up the case of small batch size or small number of heads.
[There's a blogpost coming soon]

**Comment by YichengDWu** [comment]
> For reference, the CUDA implementation now parallelizes over the seqlen_q dimension (in addition to the batch and nheads dimension), in both the forward and backward pass. It significantly speeds up the case of small batch size or small number of heads. [There's a blogpost coming soon]

Thanks for the explanation. I was wondering if you applied loop unrolling along the seqlen_v dimension?

**Comment by tridao** [comment]
There are multiple thread blocks, each thread block takes care of attention wrt 1 block of Q (e.g. 128-256 rows of Q) for 1 head and 1 batch (this is the parallelism mentioned above). To do this, each thread block loops over blocks of K and V at a time (i.e. processing attention wrt 128-256 rows of K & V).

**Comment by YichengDWu** [comment]
> There are multiple thread blocks, each thread block takes care of attention wrt 1 block of Q (e.g. 128-256 rows of Q) for 1 head and 1 batch (this is the parallelism mentioned above). To do this, each thread block loops over blocks of K and V at a time (i.e. processing attention wrt 128-256 rows of K & V).

Thanks for the reply! I understand it now!
