### ISSUE TITLE
dtype error rotary embedding

### ISSUE THREAD

**Issue by eric-tc-wong** [HazyResearch/flash-attention#42]
Hi,

I ran into dtype error when using rotary embedding. I am using fp16 but the tensor dtype get converted to float32 at apply_rotary_pos_emb().

Remove @torch.jit.script and the error disappears. This might be an issue with torchscript, but I wonder if there's a workaround.

Thanks

**Comment by tridao** [comment]
I see. I haven't been using rotary embedding recently, it was for a one-off experiment at some point. 
I adapted it from xformers's implementation (as mentioned in the source code), feel free to change it how you see it.

**Comment by eric-tc-wong** [comment]
Hi Tri Dao,

Thank you for the quick response. I don't have much experience with torch scripting so I only recast the output tensor. Please see pull request.

Thanks

**Comment by tridao** [comment]
Thanks for the PR, I've merged it.
Much appreciated!
