### ISSUE TITLE
flash_attention.py bf16

### ISSUE THREAD

**Issue by eric-tc-wong** [HazyResearch/flash-attention#44]
Hi,

Since bfloat16 was implemented, should it be allowed in FlashAttention or is fp16 preferred for extra precision?
37        assert qkv.dtype == torch.float16

Thanks

**Comment by tridao** [comment]
Yes that assert should be relaxed to allow for both fp16 and bf16.

**Comment by tridao** [comment]
I've fixed it, thanks for the catch!
