### ISSUE TITLE
Rotary Embedding Upsampled?

### ISSUE THREAD

**Issue by eric-tc-wong** [HazyResearch/flash-attention#45]
Hi Tri Dao,

Thank you for this work.
I noticed some discrepancy in the MHA output and I think I traced the issue to RotaryEmbedding.

After some testing, I find that I can reproduce the expected results by changing:

~~~
            # FlashAttention repeat (d 2) is upscaling, (2 d) is repeating channel
            # self._cos_cached = repeat(torch.cos(freqs).to(x.dtype), '... d -> ... (d 2)')
            # self._sin_cached = repeat(torch.sin(freqs).to(x.dtype), '... d -> ... (d 2)')
            self._cos_cached = repeat(torch.cos(freqs).to(x.dtype), '... d -> ... (2 d)')
            self._sin_cached = repeat(torch.sin(freqs).to(x.dtype), '... d -> ... (2 d)')
~~~

I also had to drop in rotate_half() function from GPT-NeoX to produce expected result. (https://github.com/EleutherAI/gpt-neox/blob/d7af1e7a8e3a816610b7d169456f81ca62d34ff7/megatron/model/positional_embeddings.py)

I am not sure which is the correct implementation. Is this a bug or is it more likely that I made a mistake with my input tensors?

**Comment by tridao** [comment]
The rotary embedding implementation here might be slightly different from GPT-NeoX.
As mentioned in at the top of the rotary_embedding.py file:
```# Adapted from https://github.com/facebookresearch/xformers/blob/main/xformers/components/positional_embedding/rotary.py
# We split the input differently ((d 2) -> d 2 instead of (2 d) -> d 2), following the original
# paper's implementation. This should not matter.
```
 
If you're using pretrained weight then you should use the rotary embedding implementation that matches the original weight.

If you're training from scratch I don't think it matters.

**Comment by eric-tc-wong** [comment]
I am using pretrained weights, and I wasn't sure whether the differences in results were expected. Thank you for the clarification. 
Best,
Eric
