### ISSUE TITLE
Fails to build on Windows

### ISSUE THREAD

**Issue by C43H66N12O12S2** [HazyResearch/flash-attention#50]
Flash-Attention currently fails to build on windows. There are 2 blockers:
1 - The STD needs to be set to c++17 by default, or it will fail due to static_assert `/gmem_tile.h(253): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)`
2 - MSVC quirks with std::conditional
`C:\flash-attention\csrc\flash_attn\src\fmha_fprop_fp16_kernel.sm80.cu(86): error C2975: '_Test': invalid template argument for 'std::conditional', expected compile-time constant expression`

With these two fixed, it compiles.

I "fixed" issue 2 by removing std::conditional and setting to __half, but of course that's not an actual solution - and I've no idea what is.

**Comment by bob80333** [comment]
I think I may have found the cause of 2 in this unresolved closed bug from 2018:

https://developercommunity.visualstudio.com/t/invalid-template-argument-expected-compile-time-co/187862

It seems that specifically using a constexpr variable as an input to a template fails, which is exactly what's happening with BOOL_SWITCH and std::conditional.
