### ISSUE TITLE
Hi, will it have a CPU version impl?

### ISSUE THREAD

**Issue by jinfagang** [HazyResearch/flash-attention#59]
Hi, will it have a CPU version impl?

**Comment by tridao** [comment]
We focus on reducing GPU memory reads/writes to speed up attention & save memory. The bottlenecks on CPUs are likely to be different.

**Comment by edmondja** [comment]
Could have been great for the sake of having uniform code and only change the device...

**Comment by tridao** [comment]
Sure would have been great, someone just needs to write the code
