### ISSUE TITLE
What does the `Gmem_tile_o_tmp` do in the `device_1xN_` kernel?

### ISSUE THREAD

**Issue by jundaf2** [HazyResearch/flash-attention#62]
May I ask what this 4B global memory manipulator is meant for in the FP16 (2B) kernel? 

When I commented it off, it seems the kernel still works. It is neither returned in the interface `mha_fwd`.

**Comment by tridao** [comment]
We use to store the intermediate outputs in fp32 as we accumulate it between different steps. In the final step the output is converted to fp16/bf16 and written to `Gmem_tile_o`. 
Commenting out `Gmem_tile_o_tmp` shouldn't work for seqlen > 256.

**Comment by jundaf2** [comment]
> We use to store the intermediate outputs in fp32 as we accumulate it between different steps. In the final step the output is converted to fp16/bf16 and written to `Gmem_tile_o`. Commenting out `Gmem_tile_o_tmp` shouldn't work for seqlen > 256.

Okay, I see, thanks. I set the seqlen to 64.
