### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by vibber** [HazyResearch/flash-attention#63]
Hi I'm looking forward to trying flashattention. When I try to compile on my Windows machine with rtf a5000 card I get this error:

csrc/flash_attn/fmha_api.cpp(184): error C2398: Element '1': conversion from 'int64_t' to 'c10::DeviceIndex' requires a narrowing conversion
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by vibber** [comment]
it should be noted I am on the cutlass branch and following the instructions from 
https://github.com/HazyResearch/diffusers

**Comment by tridao** [comment]
I've just pushed some fix in the `main` branch, can you try that?
I don't have a Windows machine to test but hopefully it works.

**Comment by vibber** [comment]
Hi the compilation of main worked for me now (had to get the 2019 build tools on my setup).
Could you implement the change in the cutlass branch as well? Then I'll try to see how far I get.

**Comment by DanFu09** [comment]
We should update the diffusers code some time next week to work with the main branch, that may happen faster - stay tuned!

**Comment by vibber** [comment]
great. I'll check in then.

**Comment by DanFu09** [comment]
@vibber we've updated the diffusers code to use the main branch, check out if it works better now: https://github.com/HazyResearch/diffusers

**Comment by vibber** [comment]
Hi and thanx for the update and for letting me know about it. It works
great.

-Vibeke
