### ISSUE TITLE
unable to import flash_attn_cuda

### ISSUE THREAD

**Issue by yzhaiustc** [HazyResearch/flash-attention#7]
I found I was unable to ```import flash_attn_cuda``` after running ```python setup.py install```.

--- details ---
- I run ```python setup.py install``` with a prefix pointing to the root dir of flash-attention. 
- I set ```PYTHONPATH=$PWD``` also with the absolute path of the root dir of flash-attention.

Any suggestions / comments would be greatly appreciated. Thanks a lot for your time!

ERROR MESSAGE:

```
yujia.zhai@docker-n148-083-133:~/flash-attention$ PYTHONPATH=/data00/home/yujia.zhai/flash-attention python3 benchmarks/benchmark_flash_attention.py
Traceback (most recent call last):
  File "benchmarks/benchmark_flash_attention.py", line 11, in <module>
    from flash_attn_interface import flash_attn_func
  File "/data00/home/yujia.zhai/flash-attention/flash_attn_interface.py", line 5, in <module>
    import flash_attn_cuda
```

**Comment by tridao** [comment]
Did the `python setup.py install` command finish successfully?
Compiling CUDA extension for Pytorch can be a bit tricky (e.g. sometimes the nvcc version needs to match the CUDA version that Pytorch was compiled with).
What's your nvcc version (`nvcc --version`) and Pytorch CUDA version (`torch.version.cuda`)?

I'm trying to figure out how to build wheels so that users don't have to compile the package.

**Comment by yzhaiustc** [comment]
Thanks for the response!
- ```python setup.py install``` finished successfully.
- yeah you're correct. ```torch.version.cuda```. does not match with my ```nvcc --version```. Let me try to sync them with the same cuda version and see what would be going on.

Thanks!

**Comment by yzhaiustc** [comment]
Great news! After sync the cuda versions between torch and nvcc, we've got it run.
Thank you!

**Comment by vukrosic** [comment]
Jesus spent 6 hours on this xD I'm dumb

**Comment by DevNullx64** [comment]
Hello :)
I've something like this issue.
ImportError: ~/.local/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

And torch.version.cuda: 12.1

Any idea ?
