### ISSUE TITLE
No module named `rotary_emb`

### ISSUE THREAD

**Issue by PeterZhizhin** [HazyResearch/flash-attention#71]
I can't understand which package is expected as `rotary_emb`. What do I need to install?

**Comment by tridao** [comment]
Thanks for the catch. I've updated the Pytorch interface to remove rotary embedding to avoid import errors.

**Comment by cmlakhan** [comment]
Does that mean we have to use our own positional embedding now?

**Comment by tridao** [comment]
Feel free to use your own rotary embedding. The FlashMHA module is just an example of how you would call the CUDA code.
I've switched to using this [module](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/modules/mha.py) instead (it doesn't have key_padding_mask, but that's fine for the models I train).

**Comment by cmlakhan** [comment]
I see, so I tried to write my own MHA class based on this module but when I try to import ```RotaryEmbedding``` I get an error 

```
>>> from flash_attn.layers.rotary import RotaryEmbedding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc/users/lakhac01/flash-attention/flash_attn/layers/rotary.py", line 10, in <module>
    import rotary_emb
ModuleNotFoundError: No module named 'rotary_emb'
```

I also noticed an error when trying to import ```FusedDenseTD, FusedDenseResidual```

```
>>> from flash_attn.ops.fused_dense import FusedDenseTD, FusedDenseResidual
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc/users/lakhac01/flash-attention/flash_attn/ops/fused_dense.py", line 10, in <module>
    import fused_dense_lib as fused_dense_cuda
ModuleNotFoundError: No module named 'fused_dense_lib'

```

**Comment by tridao** [comment]
Those CUDA extensions are in this repo. E.g., `csrc/fused_dense`. They are not required to run things, they're just nice to have to make things go fast. That's why the MHA class will only import them if they're available.

I'm in the middle of releasing the optimized model implementation so the installation instructions aren't there yet.

**Comment by RuABraun** [comment]
One can just remove the line `import rotary_emb`. Think that is the real issue everyone here was stumbling across

**Comment by CandideThunder** [comment]
I run into that issue when installing evo / flash-attention. It can be solved by installing triton manually, e.g.:
`conda install triton`
