### ISSUE TITLE
Extension for encoder-decoder attention

### ISSUE THREAD

**Issue by quanpn90** [HazyResearch/flash-attention#8]
Hello and thanks for your work.

I wonder if this algorithm can be extended to use for encoder-decoder attention.

In the decoder, I guess it is possible to unpad -> self-attention -> pad again to deal with the subsequent EDA. However, is it possible to implement EDA using this method, such that both queries and (keys values) are unpadded? 

Thanks!

**Comment by tridao** [comment]
Yes, I think we can support encoder-decoder attention.
Is the difference that Q can have different sequence length compared to K & V?

**Comment by quanpn90** [comment]
Yes, that is the only difference as far as I can tell. Thank you for the answer

**Comment by tridao** [comment]
I see. And would Q also have a padding mask in case the query sequences in the batch have different lengths?

**Comment by tridao** [comment]
You're right, it doesn't affect the result. We've been focusing on speed / memory so ideally we'd avoid redundant computation.
I haven't used cross attention much so I'm just trying to understand how it's used. Maybe in translation decoding Q might have a mask? I'm not sure.

In any case I'll try to find some time this weekend to implement it. Should be straightforward (hopefully).

**Comment by quanpn90** [comment]
In most translation decoders Q don't have masking simply because the sequences are padded to the right, so causal masking is just enough. Its trivial to make such mask though, to remove the redundant computation.

**Comment by quanpn90** [comment]
oh by the way, I am not an expert in low level optimization. But from reading your paper, I understand that it is possible to fuse the gemm - gelu/relu- dropout - gemm in one kernel?

In your paper, the 3x speed up compared to a HF baseline is done only with flashattention and without any optimization in layernorm/FFN/softmax, is it correct?

**Comment by tridao** [comment]
Gemms are hard to fuse because each output element depends on many input elements, so you have to figure out how to parallelize the computation the right way. Moreover, gemms tend to be compute-bound and not memory-bound. Nvidia has done some work on fusing Gemm + ReLU/GELU in [cuBlasLT](https://docs.nvidia.com/cuda/cublas/index.html#cublasLtEpilogue_t). I'm not aware of any implementation that can fuse gemm + activation + another gemm in the FFN layer into one kernel.

In our GPT2 implementation we use FlashAttention and a standard FFN layer. You can probably get even more speedup if you fuse Gemm + GELU.

**Comment by quanpn90** [comment]
Oh NVIDIA CUTLASS has some examples for fusing 2 gemms.

https://github.com/NVIDIA/cutlass/tree/master/examples/13_two_tensor_op_fusion

Thanks for the answer! Crossing fingers for the cross attention.

**Comment by tridao** [comment]
I see, thanks for the pointer! Let me check it out.

**Comment by quanpn90** [comment]
I was thinking about trying to implement this, starting from the set_params function

https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/fmha_api.cpp#L33

If we have Q and KV of different lengths, then we need max_s and cu_seqlens for each (assuming Q and KV are unpadded)? I don't really understand how the algorithm works with unpadded tensors, do you need to rearrange and pad them, like this figure: (From Effective Transformer)

https://github.com/bytedance/effective_transformer/blob/master/images/1.png

**Comment by tridao** [comment]
FasterTransformer also has an [illustration](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/images/effective_transformer.png).
Our `cu_seqlens` is essentially their sequence length offset.

You're right, we'll need max_s and cu_seqlens for each. The CUDA code only works on unpadded tensors and assumes that the [unpadding](https://github.com/HazyResearch/flash-attention/blob/765741c1eeb86c96ee71a3291ad6968cfbf4e4a1/flash_attn/flash_attention.py#L59) step is done outside.

I've started to refactor the code that reads/writes from/to global memory to store pointers to Q, K, V separately. 
Got caught up thinking about some other technical problem so I didn't finish the cross-attention stuff yet.
Hopefully this week or next.

**Comment by quanpn90** [comment]
Thank you for the implementation of the general case with Q and KV separated :)
