### ISSUE TITLE
Reproduce the speed up performance

### ISSUE THREAD

**Issue by OrangeSodahub** [HazyResearch/flash-attention#81]
Hi, thanks for your great work.
I tried to use flash attention in some popular models. In [here](https://github.com/OrangeSodahub/Openclip-flashattn), I benchmark the performance between with and without flash attention based on the openclip model. However, what confused me most is that I cannot reproduce the speed-up performance shown in your work (up to 2x ~ 4x), and it is worse (~1.1x).
Could you give some advice on how to perfectly achieve your excellent speed-up?
BTW, could you give more details about your experiments on the comparison of flashattn and torch? For example, what parts exactly be counted in your experiments, is it just those three steps or else? As you can see in our benchmarks, we only replace the computation of the attention part and almostly get the correct result, and count the time cost of the entire model (there only exist differences on the part which is replaced theoretically).

**Comment by tridao** [comment]
The easiest way is to benchmark just the attention module. We have a script to do that [here](https://github.com/HazyResearch/flash-attention/blob/main/benchmarks/benchmark_flash_attention.py). We see 2-4x speedup on the attention module. Other folks have also observed around the same speedup on their hardware.

When you plug it into a model and measure end-to-end speed, it depends on whether attention is the bottleneck in the model. For example, if the model only spends 10% of the time in attention (e.g., you're dealing with short sequences), then the most end-to-end speedup you can get is 1.0 / 0.9 = 1.11x. You can [profile](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html) your model to see what the bottlenecks are. What's the sequence length in your application?

I haven't used openclip models but we have an optimized [implementation](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/models/vit.py) of GPT2/3 and ViT in this repo. I'm in the middle of cleaning up the training code for release as well.

**Comment by OrangeSodahub** [comment]
Thanks a lot! You've made me understand a lot of things.
