### ISSUE TITLE
Getting the attention score matrix during inference

### ISSUE THREAD

**Issue by zzk1st** [HazyResearch/flash-attention#83]
Hi, we are using flash attention in our language model training and it's super fast, thanks for the great work!

We have a question about the attention score matrix though. During one of our downstream tasks, we need the attention score matrix as the input of another model. But my understanding is, Flash Attention has fused the QV->softmax->V operations, so there's no way to get the attention score matrix using flash attention during inference. In this case, what would you recommend to do? is it possible to train the LM using flash attention, while during inference use a standard attention?

Many thanks in advance!

**Comment by tridao** [comment]
Thanks, I'm glad to see our work has been useful.

Yes, FlashAttention and standard attention are interchangeable (they compute the same thing), so you can use FlashAttention for training and standard attention for inference if you need the softmax.
