### ISSUE TITLE
[Question] how to deal with batch_first=False

### ISSUE THREAD

**Issue by SeaOfOcean** [HazyResearch/flash-attention#84]
Hi, thanks for the great work!

I have a question: the default input to the attention is batch in the first dimension.
But many models have sequence is the first dimension, batch second. How can I adjust the kernel to support the sequence_first input without input transpose? 

Thanks!

**Comment by tridao** [comment]
The simplest way is to just transpose the input. If the model is large then input transposition doesn't take much time compared to attention and MLP.

If you want to change the CUDA code to deal with sequence_first, the logic for that is [here](https://github.com/HazyResearch/flash-attention/blob/0bf5e50038ee341ece03bfd0c8ff45a6c57aed5a/csrc/flash_attn/src/fmha/gmem_tile.h#L89) for Gmem_tile_qkv (and similarly for Gmem_tile_o).
Right now it computes the offset into the sequence by taking the cumulative sequence length up to the current sequence (equivalently sequence_length * currrent_sequence_idx if all sequences have the same length).
You can instead compute the offset as current_batch_idx * batch_size if your inputs have the form (seqlen, batch, nheads, headdim).
