### ISSUE TITLE
Speed up the build / make it parallel?

### ISSUE THREAD

**Issue by vedantroy** [HazyResearch/flash-attention#85]
Is there anyway to make the build parallel / speed it up more generally? Building flash attention is generally the slowest part of my Docker setup. I have a 64-core computer, but it seems like usually ~ 1 core is being used.

Would installing something like ninja help?

**Comment by vedantroy** [comment]
Ok, I think forcing flash_attention to use ninja helped, with `BuildExtension.with_options(use_ninja=True)`

**Comment by tridao** [comment]
[Recently](https://github.com/HazyResearch/flash-attention/commit/d95ee1a95da2b138073b5eef0f09ce4de615ba5e) I split the code into multiple .cu files to speed up compilation.
It should use ninja by default if ninja is available. I don't think you need to force `use_ninja=True` (but then again I'm not experienced in compilation and I could be wrong).

**Comment by vedantroy** [comment]
Hm, the build has certainly gotten faster: 600s => 280s.
One thing I notice, is that it seems like at the start of the build that multiple cores are being used, and then there's still a pretty long phase where a single/1.5?? cores are being used.

Do you think that there's a particularly long linking phase or something like that?

Regardless, I'll close the issue since the build seems to be parallelized.

**Comment by tridao** [comment]
It's building a several kernels in parallel, so at the end there's a kernel that takes a long time that's still compiling (backward pass for head dim 64).
