### ISSUE TITLE
Explanation of some layer names?

### ISSUE THREAD

**Issue by vedantroy** [HazyResearch/flash-attention#87]
I'm trying to make a reversible video-transformer using Flash Attention and I've been peeking through some of the layers in the models folder. I had a few questions that I would greatly appreciate if you could answer.

1. What does "TD" stand for in the layer names?
2. Compared to flash attention itself, what do the other speedups (i.e using fused layer norm / dropout / add) contribute--especially if you're not using dropout? I'm mostly wondering if the 80/20 is to just use the flash attention optimization.
3. It seems like the dropout + add + ln optimization calls `dropout_add_layer_norm` twice (I think?)

https://github.com/HazyResearch/flash-attention/blob/4a6eaa9f27df6fff7ffb2c24e894938a687dd870/flash_attn/modules/block.py#L107

https://github.com/HazyResearch/flash-attention/blob/4a6eaa9f27df6fff7ffb2c24e894938a687dd870/flash_attn/modules/block.py#L124

why would that be the case? (Or maybe I'm missing something & when the optimization is enabled, the `mlp` becomes an `nn.Identity`.

Thanks!

**Comment by tridao** [comment]
> 1. What does "TD" stand for in the layer names?

It's my initials 🤣

> 2. Compared to flash attention itself, what do the other speedups (i.e using fused layer norm / dropout / add) contribute--especially if you're not using dropout? I'm mostly wondering if the 80/20 is to just use the flash attention optimization.

Yes most of the speedup is from FlashAttention. The exact numbers depend on the model dimensions and so on. Feel free to play with the flags.

> 3. It seems like the dropout + add + ln optimization calls `dropout_add_layer_norm` twice (I think?)
> 
> https://github.com/HazyResearch/flash-attention/blob/4a6eaa9f27df6fff7ffb2c24e894938a687dd870/flash_attn/modules/block.py#L107
> 
> https://github.com/HazyResearch/flash-attention/blob/4a6eaa9f27df6fff7ffb2c24e894938a687dd870/flash_attn/modules/block.py#L124
> 
> why would that be the case? (Or maybe I'm missing something & when the optimization is enabled, the `mlp` becomes an `nn.Identity`.

Yes, it calls it twice. Once after the attention part, once after the MLP part, as is standard.
