### ISSUE TITLE
Suggestion for XPos implementation

### ISSUE THREAD

**Issue by sunyt32** [HazyResearch/flash-attention#96]
https://github.com/HazyResearch/flash-attention/blob/496e4f528c647aa29fb5fb8e8e989078ebe7ef6c/flash_attn/layers/rotary.py#L142
"scale_base" here aims to avoid numerical overflow. If it's set as an arbitrary value such as 1, the problem will occur.  A recommended value makes it work better such as 512.

**Comment by tridao** [comment]
Thanks Yutao! I've changed it to note that scale_base is recommended to be 512.
Great work on XPos! Btw lucidrains also has it implemented in his [repo](https://github.com/lucidrains/x-transformers/blob/b0237b01e96f73459c66beef6d41b59fb17de612/x_transformers/x_transformers.py#L381).
