### ISSUE TITLE
No module named 'fused_dense_lib'

### ISSUE THREAD

**Issue by syorami** [HazyResearch/flash-attention#97]
I was trying to use `fused_dense_gelu_dense_func` but the function gives me error `No module named 'fused_dense_lib'`. Did I miss sth to install?

**Comment by tridao** [comment]
You can do `cd csrc/fused_dense_lib && pip install .` to install as mentioned [here](https://github.com/HazyResearch/flash-attention/tree/main/training#model-components).
Let me know if that doesn't work.

**Comment by syorami** [comment]
This works for me after building from source code. It would be better if these installation instructions can be mentioned in `README.md` under the root.
