### ISSUE TITLE
Support for FLASH: Gated Attention Unit 

### ISSUE THREAD

**Issue by mistycube** [HazyResearch/flash-attention#98]
Is it possible in the flash attention interface to handle gated single head attention ?
Maybe the speedup can be even higher.

Paper: https://arxiv.org/pdf/2202.10447.pdf

**Comment by tridao** [comment]
We don't have that out of the box. Feel free to play with the Triton [implementation](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_triton.py) (it's a self-contained Python file).

**Comment by mistycube** [comment]
Sure. Thanks for your prompt reply.
